### ISSUE TITLE
Выбрать предмет

### ISSUE THREAD

**Issue by Ysmur** [Ma1ozem0v/website_on_Python-learning-platform-#6]
Согласно информации от Елены Александровны необходимо каждому выполнять индивидуальный проект. Поэтому каждый выбирает себе свой предмет (математика, физика и т.д.). Здесь в комментарии зафиксировать свой выбор.

**Comment by Ma1ozem0v** [comment]
Физика

**Comment by MaRiAyakimovich** [comment]
Русский язык
